# Generated by Django 3.1.4 on 2021-06-26 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(db_column='fname', max_length=25)),
                ('mname', models.CharField(db_column='mname', max_length=25)),
                ('lname', models.CharField(db_column='lname', max_length=25)),
                ('gender', models.CharField(db_column='gender', max_length=25)),
                ('streetaddress', models.CharField(db_column='streetaddress', max_length=30)),
                ('city', models.CharField(db_column='city', max_length=25)),
                ('state', models.CharField(db_column='state', max_length=2)),
                ('zipcode', models.CharField(db_column='zipcode', max_length=5)),
                ('email', models.CharField(db_column='email', max_length=50)),
                ('phone', models.CharField(db_column='phone', max_length=12)),
                ('country', models.CharField(db_column='country', max_length=25)),
                ('dob', models.CharField(db_column='dob', max_length=20)),
                ('age', models.CharField(db_column='age', max_length=3)),
            ],
            options={
                'db_table': 'register',
                'managed': False,
            },
        ),
    ]
