# Generated by Django 3.1.4 on 2021-06-26 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
